### Running multiple parallel chains with BGLR

For problems involving large number of predictors and large number of subjects the time per itearation of the sampler may be large (e.g, a ccouple of seconds)
and running long chains may take too much time. In these cases, and especially when one has acces to a computing cluster, running multiple parallel short chains
may be a better option than runnin a single long chain. 

However, in big problems the burn-in period can be large. This can be overcomed if one uses as initial values samples generated by another
chain collected after burn in. Before the Gibbs sampler starts BGLR carries out many computations that make the sampler more effient. These
computations also take some time that can be saved if we were able to 'recycle' the results from these computations from a previous run.

To achieve this goal we propose to modify BGLR in a very simple way, we will modify BGLR so that:  

  - if specified by the user, the program can save the environment,
  - if the call provides a filename for an environment, BGLR will load the environment and start the gibbs sampler.
          
Conceptually, the BGLR code can be divided in the following blocks

  -
          
